#!/bin/bash
set -euo pipefail

echo "Inicializando esquema ${APP_USER}..."

sqlplus -s / as sysdba <<EOF
WHENEVER SQLERROR EXIT SQL.SQLCODE

ALTER SESSION SET CONTAINER = FREEPDB1;

DECLARE
  v_user_count NUMBER := 0;
  v_table_count NUMBER := 0;
  v_column_count NUMBER := 0;
  v_constraint_count NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO v_user_count
    FROM dba_users
   WHERE username = UPPER('${APP_USER}');

  IF v_user_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER ${APP_USER} IDENTIFIED BY "${APP_USER_PASSWORD}"';
    EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO ${APP_USER}';
    EXECUTE IMMEDIATE 'GRANT UNLIMITED TABLESPACE TO ${APP_USER}';
  END IF;

  SELECT COUNT(*)
    INTO v_table_count
    FROM all_tables
   WHERE owner = UPPER('${APP_USER}')
     AND table_name = 'INSURANCE';

  IF v_table_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE ${APP_USER}.insurance (
      ID NUMBER(19,0) NOT NULL,
      POLICY VARCHAR2(255 CHAR),
      PLAQUE VARCHAR2(255 CHAR),
      ISSUE_DATE TIMESTAMP(6),
      CUSTOMER_ID VARCHAR2(255 CHAR),
      PRIMARY KEY (ID)
    )';
  ELSE
    SELECT COUNT(*)
      INTO v_column_count
      FROM all_tab_columns
     WHERE owner = UPPER('${APP_USER}')
       AND table_name = 'INSURANCE'
       AND column_name = 'POLICY';

    IF v_column_count = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE ${APP_USER}.insurance ADD (POLICY VARCHAR2(255 CHAR))';
    END IF;
  END IF;

  SELECT COUNT(*)
    INTO v_table_count
    FROM all_tables
   WHERE owner = UPPER('${APP_USER}')
     AND table_name = 'NOTIFICATION_EMISSION';

  IF v_table_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE ${APP_USER}.notification_emission (
      ID NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      CHANNEL VARCHAR2(255 CHAR),
      MESSAGE VARCHAR2(255 CHAR),
      STATUS VARCHAR2(255 CHAR),
      CREATE_AT TIMESTAMP(6) NOT NULL,
      UPDATE_AT TIMESTAMP(6) NOT NULL,
      INSURANCE_ID NUMBER(19,0) NOT NULL,
      PRIMARY KEY (ID),
      CONSTRAINT FK_NOTIFICATION_EMISSION_INSURANCE
        FOREIGN KEY (INSURANCE_ID) REFERENCES ${APP_USER}.insurance (ID)
    )';
  ELSE
    SELECT COUNT(*)
      INTO v_column_count
      FROM all_tab_columns
     WHERE owner = UPPER('${APP_USER}')
       AND table_name = 'NOTIFICATION_EMISSION'
       AND column_name = 'CHANNEL';

    IF v_column_count = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE ${APP_USER}.notification_emission ADD (CHANNEL VARCHAR2(255 CHAR))';
    END IF;

    SELECT COUNT(*)
      INTO v_column_count
      FROM all_tab_columns
     WHERE owner = UPPER('${APP_USER}')
       AND table_name = 'NOTIFICATION_EMISSION'
       AND column_name = 'MESSAGE';

    IF v_column_count = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE ${APP_USER}.notification_emission ADD (MESSAGE VARCHAR2(255 CHAR))';
    END IF;

    SELECT COUNT(*)
      INTO v_column_count
      FROM all_tab_columns
     WHERE owner = UPPER('${APP_USER}')
       AND table_name = 'NOTIFICATION_EMISSION'
       AND column_name = 'STATUS';

    IF v_column_count = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE ${APP_USER}.notification_emission ADD (STATUS VARCHAR2(255 CHAR))';
    END IF;

    SELECT COUNT(*)
      INTO v_column_count
      FROM all_tab_columns
     WHERE owner = UPPER('${APP_USER}')
       AND table_name = 'NOTIFICATION_EMISSION'
       AND column_name = 'CREATE_AT';

    IF v_column_count = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE ${APP_USER}.notification_emission ADD (CREATE_AT TIMESTAMP(6))';
    END IF;

    SELECT COUNT(*)
      INTO v_column_count
      FROM all_tab_columns
     WHERE owner = UPPER('${APP_USER}')
       AND table_name = 'NOTIFICATION_EMISSION'
       AND column_name = 'UPDATE_AT';

    IF v_column_count = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE ${APP_USER}.notification_emission ADD (UPDATE_AT TIMESTAMP(6))';
    END IF;

    SELECT COUNT(*)
      INTO v_column_count
      FROM all_tab_columns
     WHERE owner = UPPER('${APP_USER}')
       AND table_name = 'NOTIFICATION_EMISSION'
       AND column_name = 'INSURANCE_ID';

    IF v_column_count = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE ${APP_USER}.notification_emission ADD (INSURANCE_ID NUMBER(19,0))';
    END IF;

    SELECT COUNT(*)
      INTO v_constraint_count
      FROM all_constraints
     WHERE owner = UPPER('${APP_USER}')
       AND table_name = 'NOTIFICATION_EMISSION'
       AND constraint_type = 'R'
       AND constraint_name = 'FK_NOTIFICATION_EMISSION_INSURANCE';

    IF v_constraint_count = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE ${APP_USER}.notification_emission
        ADD CONSTRAINT FK_NOTIFICATION_EMISSION_INSURANCE
        FOREIGN KEY (INSURANCE_ID) REFERENCES ${APP_USER}.insurance (ID)';
    END IF;
  END IF;
END;
/

MERGE INTO ${APP_USER}.insurance t
USING (
  SELECT 1 AS id, '10001' AS policy, '10987654' AS customer_id, 'ABC123' AS plaque,
         TIMESTAMP '2026-03-01 08:30:00' AS issue_date
  FROM dual
  UNION ALL
  SELECT 2 AS id, '10002' AS policy, '20456789' AS customer_id, 'XYZ987' AS plaque,
         TIMESTAMP '2026-03-01 09:45:10' AS issue_date
  FROM dual
  UNION ALL
  SELECT 3 AS id, '10003' AS policy, '30999888' AS customer_id, 'MNO456' AS plaque,
         TIMESTAMP '2026-03-01 11:20:35.123456' AS issue_date
  FROM dual
) s
ON (t.id = s.id)
WHEN NOT MATCHED THEN
  INSERT (id, policy, customer_id, plaque, issue_date)
  VALUES (s.id, s.policy, s.customer_id, s.plaque, s.issue_date);

MERGE INTO ${APP_USER}.notification_emission t
USING (
  SELECT 'EMAIL' AS channel, 'Notificacion enviada por correo' AS message, 'SUCCESSFUL' AS status,
         TIMESTAMP '2026-03-01 08:35:00' AS create_at,
         TIMESTAMP '2026-03-01 08:35:00' AS update_at, 1 AS insurance_id
  FROM dual
  UNION ALL
  SELECT 'SMS' AS channel, 'Notificacion en cola para envio por SMS' AS message, 'PENDING' AS status,
         TIMESTAMP '2026-03-01 09:50:10' AS create_at,
         TIMESTAMP '2026-03-01 09:50:10' AS update_at, 2 AS insurance_id
  FROM dual
  UNION ALL
  SELECT 'WEBSERVICE' AS channel, 'Fallo el envio al servicio externo' AS message, 'FAILED' AS status,
         TIMESTAMP '2026-03-01 11:25:35.123456' AS create_at,
         TIMESTAMP '2026-03-01 11:25:35.123456' AS update_at, 3 AS insurance_id
  FROM dual
) s
ON (
  t.insurance_id = s.insurance_id
  AND t.channel = s.channel
  AND t.status = s.status
  AND t.message = s.message
)
WHEN NOT MATCHED THEN
  INSERT (channel, message, status, create_at, update_at, insurance_id)
  VALUES (s.channel, s.message, s.status, s.create_at, s.update_at, s.insurance_id);

COMMIT;
EXIT;
EOF

echo "Inicializacion de Oracle completada."
